@startuml
'https://plantuml.com/class-diagram

Class Animal {
alive: bool = True
eat():void
sleep():void
}

hide Rabbit fields
Class Rabbit {
run():void
}

Class Fish {
swim():void
}

Class Hawk {
fly():void
}

Animal <|-- Hawk
Animal <|-- Fish
Animal <|-- Rabbit
@enduml